#!/usr/bin/bash



con="ubuntu:latest"
vol=''

while getopts ":c:v:" opt; do
  case $opt in
    c) con="$OPTARG"
    ;;
    v) vol="-v $OPTARG:/local"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

podman run -it --rm $vol $con bash
